eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8084
spring:
  application:
    name: service-feign
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  #请求处理的超时时间
ribbon:
  ReadTimeout: 10000
    #请求连接的超时时间
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true

